bluerobotics/ping-protocol

src/protocol/.gitignore
=> Add gitignore for generated folder and files

src/sensor/ping.cpp, src/sensor/ping.h
=> ping: Add option to send ping_goto_bootloader in firmwareUpdate

src/protocol/templates/ping_protocol.json
This is a update based on the last commit with the protocol class.
bfe9c082a5e595d287b74ac2f8758a895137feb9
=> Protocol corrections

src/link/pingsimulationlink.cpp
=> PingSimulationLink: Update simulation to use correct depth

src/protocol/generator.py, src/protocol/templates/ping_protocol.json, src/protocol/templates/pingmessage_.h.in
The template can use a vector array with "var" size:
```js
"payload": [
{
"name": "id_to_nack",
"type": "u16"
},
{
"name": "err_msg",
"type": "u8[var]"
}
]
```
The output is:
```cpp
class ping_msg_ping1D_nack : public PingMessage
{
public:
ping_msg_ping1D_nack(QByteArray& buf) : PingMessage(buf) {}
ping_msg_ping1D_nack(PingMessage& msg) : PingMessage(msg) {}
ping_msg_ping1D_nack() {
msgData = std::vector<uint8_t>(8 + 2 + 0 /*cant send var size*/ + 2, 0);
msgData[0] = 'B';
msgData[1] = 'R';
(uint16_t&)msgData[2] = 2 + 0 /*cant send var size*/; // payload size
(uint16_t&)msgData[4] = 2; // ID
msgData[6] = 0;
msgData[7] = 0;
}
uint16_t id_to_nack() { uint16_t d; memcpy(&d, (payload_data(0)), 2); return d; };
void set_id_to_nack(uint16_t id_to_nack) { memcpy((payload_data(0)), &id_to_nack, …
```
=> Get dynamic string sizes

src/protocol/parsers/detector.cpp, src/protocol/parsers/detector.h, src/protocol/protocol.pri
- Scan only valid ports
- Add timeout to open ports
=> Improve detector

src/link/abstractlink.h, src/link/filelink.cpp, src/link/filelink.h, src/link/seriallink.cpp, src/link/seriallink.h, src/link/udplink.cpp, src/link/udplink.h, src/protocol/parsers/detector.cpp, src/protocol/parsers/detector.h
=> Update all link strings to string list

src/link/pingsimulationlink.cpp, src/protocol/generator.py, src/protocol/parsers/detector.cpp, src/protocol/parsers/parser_ping.h, src/protocol/templates/ping_protocol.json, src/protocol/templates/pingmessage.h.in, src/protocol/templates/pingmessage_.h.in
- Remove vector dependency
- Remove string dependency
- The resulting code runs well in both pingviewer and arduino
- Fix #42
=> Message v2

src/protocol/parsers/detector.cpp
=> ProtocolDetector: Add check for interruptionRequest

src/protocol/templates/pingmessage_.h.in
=> pingmessage: Add uint8_t* array constructor

src/protocol/parsers/parser_ping.h
=> parser: bugfix for 0 length payload handling

src/protocol/templates/pingmessage.h.in
=> pingmessage: Correct problem with wrong checksum calculated address

src/protocol/templates/pingmessage.h.in
=> PingMessage: Update empty message

.travis.yml
=> travis: Correct protocol test

src/protocol/README.md
=> README: Add build status

README.md, src/protocol/README.md, src/protocol/templates/ping_doc.in
=> README: Correct badges file localization

README.md
Update generated file from 953ba72950e0a3b729ec5074c992a0ca1787e112
=> Fix documentation test

.appveyor.yml, .travis.yml, ping.pri, src/link/abstractlink.cpp, src/link/abstractlink.h, src/link/abstractlinknamespace.h, src/link/filelink.cpp, src/link/filelink.h, src/link/link.cpp, src/link/link.h, src/link/link.pri, src/link/linkconfiguration.cpp, src/link/linkconfiguration.h, src/link/seriallink.cpp, src/link/seriallink.h, src/link/udplink.cpp, src/link/udplink.h, src/protocol/parsers/detector.cpp, src/protocol/parsers/detector.h
This PR add a major abstraction layer under link configuration:
- Adds LinknConfiguration class
- Adds AbstractLinkNamespace for connection types (avoid cyclical dependencies)
- Helps graphic interfaces to deal with configuration in a more high level way
=> New connect configuration method

src/link/filelink.cpp, src/link/filelink.h, src/protocol/parsers/detector.h, src/protocol/parsers/parser.h, src/protocol/parsers/parser_json.cpp, src/protocol/parsers/parser_json.h, src/protocol/parsers/parser_ping.h
=> Use smart pointer when necessary and some random fixes

.travis.yml
=> travis: Fix bug with TEST variable

.travis.yml
=> travis: Fix tests

.travis.yml
This fixes using "set" for atributes like in `object.atribute = something`
=> Bump Jinja2 version

src/protocol/templates/_all.h.in, src/protocol/templates/ping1d.cpp.in, src/protocol/templates/ping1d.py.in, src/protocol/templates/pingmessage.h.in, src/protocol/templates/pingmessage.py.in, src/protocol/templates/pingmessage_.h.in
=> Sort the messages when generating code

src/protocol/templates/ping1d.py.in, src/protocol/templates/pingmessage.py.in
According to https://github.com/bluerobotics/ping-python/commit/7d54b7c287fdd6b21262cc0e6e4d7420a2a8c3d7
=> python: use env for shebang

src/protocol/templates/ping1d.py.in
ord also does not work with lists
=>  ping1d: Remove ord since is not necessary in python3

src/protocol/templates/pingmessage.py.in
=> pingmessage: ord is not necessary

src/protocol/generate-arduino.py, src/protocol/generate-python.py, src/protocol/generator.py, src/protocol/templates/ping1d.cpp.in, src/protocol/templates/ping1d.h.in, src/protocol/templates/pingmessage.h.in, src/protocol/templates/pingmessage.py.in, src/protocol/templates/pingmessage_.h.in
This PR do a small organization with the generator scripts.
Move a bunch of redundant functions to a common class called Generator.
=> Create and use generator class

README.md, src/protocol/templates/ping_protocol.json
Fix https://github.com/bluerobotics/ping-protocol/issues/88
=> Add general_request

src/protocol/generate-arduino.py, src/protocol/generate-doc.py, src/protocol/generate-python.py
=> generate-doc,python,arduino: Remove re import

tools/update-generated-repositories.sh
=> update-generated-repositories: Fix python call

README.md, src/protocol/definitions/ping360.json, src/protocol/templates/ping_doc.in
- Update parameters message.
- Update 2303 and add new messages 2305, 2306.
- Move from SS1 to Ping360.
=> Ping360 definition: Update to follow new specs

src/protocol/generate-arduino.py, src/protocol/generate-python.py
=> protocol: Remove collections import from python and arduino script

src/protocol/templates/pingmessage.py.in
related to (but not dependent on): https://github.com/bluerobotics/ping-python/pull/61
=> pingmessage.py: bugfix self.message_id reference

README.md, src/protocol/templates/ping_doc.in
Fix https://github.com/bluerobotics/ping-protocol/issues/145
=> Add pack and unpack example

README.md, src/protocol/definitions/common.json, src/protocol/definitions/ping360.json, test/test.cpp.in, tools/run-tests.sh
=> Ping360 overhaul

src/generator.py
=> generator: Allow dict input as definition

docs/index.md
check the mistake: http://docs.bluerobotics.com/ping-protocol/
=> index.md: fix formatting

src/definitions/ping360.json
=> ping360: Update auto_transmit definition

src/definitions/common.json
=> definitions: common: Add set device ID

src/definitions/ping360.json
=> definitions: ping360: Add NOT RELEASED tag in auto_device_data

src/definitions/ping1d.json, src/definitions/ping360.json
Add information about array organization
=> definitions: Improve description about profile array

src/definitions/ping1d.json
* Add set_oss_profile_configuration message
* Add oss_profile_configuration message
=> src: definitions: ping1d: Add OSS messages
